In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
l = range(1000)
%timeit [i**2 for i in l]

204 μs ± 17.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
a = np.arange(1000)
%timeit a** 2

3.05 μs ± 285 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Arrays

In [11]:
a = np.array([1,2,3,4])           # one dimension array
print(a.ndim)

1


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [13]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c.ndim)

3


In [15]:
print(a.shape)

(4,)


In [16]:
print(b.shape)

(2, 3)


In [17]:
print(c.shape)

(1, 3, 3)


# Functions of Creating Array

In [3]:
a = np.array(10)
print(a)

10


In [4]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [5]:
# using linspace
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [6]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
print(np.diag(a))

[1 2 3 4]


# Basic DataTypes

In [12]:
a = np.arange(10)
print(a.dtype)

int64


In [14]:
a = np.arange(10, dtype="float64")
print(a.dtype)

float64


# Other DataTypes

In [15]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [16]:
a = np.array([True,False])
print(a.dtype)

bool


In [17]:
a = np.array(["Yashmitha","Krishna"])
print(a.dtype)

<U9


# Indexing & Slicing

In [18]:
a = np.arange(10)
print(a[5])

5


In [20]:
a = np.arange(2,20,2)
print(a[2])

6


In [21]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [22]:
a[2,1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# Slicing

In [23]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(a[1:8:2])

[1 3 5 7]


In [26]:
print(a[2:8:2])

[2 4 6]


# Copies And Viewing

In [27]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [28]:
print(np.shares_memory(a,b))

True


In [29]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [30]:
a = np.arange(10)
b = a[::2].copy()   # Force copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [31]:
print(np.shares_memory(a,b))

False


In [32]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random Number Generator

In [33]:
a = np.random.randint(0,20,15)
print(a)

[ 4 15 17  9 16 19 19 14 11  2  9  6 10 17 16]


# Element Wise operations

# 1.Basic Opertions

In [34]:
a = np.array([1,2,3,4])
print(a+1)   # add+1

[2 3 4 5]


In [35]:
print(a**2)

[ 1  4  9 16]


# All Arithemetic Operates ElementWise

In [36]:
b = np.ones(4)+1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [37]:
print(a*b)

[2. 4. 6. 8.]


# Comparision Operators

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,2,7,4])
print(a == b)

[False  True False  True]


In [39]:
print(a<b)

[ True False  True False]


In [40]:
print(a>b)

[False False False False]


In [41]:
# Array Wise Comparision
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [42]:
print(np.array_equal(a,c))

True


# Logical Operators

In [43]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,1,0,0],dtype = "bool")

In [44]:
print(np.logical_or(a,b))

[ True  True  True False]


In [45]:
print(np.logical_and(a,b))

[ True False False False]


# Trignometry

In [47]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [48]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [49]:
print(np.cos(a))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [50]:
np.log(a)

C:\Users\yashm\AppData\Local\Temp\ipykernel_19948\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [51]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
